In [148]:

import time      # for testing use only
import os         # for testing use only

import bs4
from bs4 import BeautifulSoup  
import pandas as pd
import scipy as sc
import numpy as np
import requests 
import matplotlib as mpl
from matplotlib import pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
mpl.rcParams['figure.dpi'] = 300

In [2]:

##function load site
def load_soup_object(url):
    page = requests.get(url)
    page
    soup = BeautifulSoup(page.content, 'html.parser')
    return soup

In [3]:
year=[]
model=[]
make=[]
km=[]
accident=[]
owner=[]
use=[]
price=[]
color=[]
###############

############
soup=load_soup_object("https://www.truecar.com/used-cars-for-sale/listings/")##load site
               

for i in range(220):
    relevant=soup.findAll("div",attrs={"class":"flex w-full flex-col"})## all the cars
    for par in relevant:

        #color
        h5s=par.find(attrs={"data-test":"vehicleCardColors"})
        string_h5s = [tag.get_text() for tag in h5s]
        color1=string_h5s[1]
        color.append(color1)


        #price
        h4s=par.find(attrs={"data-test":"vehicleCardPricingBlockPrice"})
        string_h4s = [tag.get_text() for tag in h4s]
        price1=string_h4s[0]
        price.append(price1)


        #year
        year.append(par.find("span",attrs={"class":"vehicle-card-year text-xs"}).string)


        #accident&&owner&&use
        h3s=par.find(attrs={"data-test":"vehicleCardCondition"})
        string_h3s = [tag.get_text() for tag in h3s]
        arr=string_h3s[1].split(",")
        accident1=arr[0]
        owner1=arr[1]
        use1=arr[2]
        accident.append(accident1)
        owner.append(owner1)
        use.append(use1)



        #km
        h2s=par.find(attrs={"data-test":"vehicleMileage"})
        string_h2s = [tag.get_text() for tag in h2s]
        km.append(string_h2s[1])

        #make&&model
        h1s=par.find("span",attrs={"class":"truncate"})
        string_h1s = [tag.get_text() for tag in h1s]
        make.append(string_h1s[0])
        model.append(string_h1s[4])
        
    #next_page
    nextUrl=soup.find("a", attrs={"aria-label":"Go to next page"})['href']##url to the next page
    next_url="https://www.truecar.com"+nextUrl
    soup= load_soup_object(next_url)

df=pd.DataFrame({"year":year,"make":make,"model":model,"km":km,"accident":accident,"owner":owner,"use":use,"color":color,"price":price})

In [4]:
df

,year,make,model,km,accident,owner,use,color,price
0,2018,Land Rover,Discovery Sport,"64,126",No accidents,2 Owners,Personal use,Silver,"$22,288"
1,2017,Chevrolet,Cruze,"119,174",No accidents,2 Owners,Personal use,Blue,"$14,999"
2,2007,Porsche,Cayman,"15,565",No accidents,2 Owners,Personal use,White,"$43,998"
3,2019,Chevrolet,Equinox,"36,179",No accidents,1 Owner,Personal use,White,"$18,900"
4,2020,Toyota,Corolla,"60,821",No accidents,1 Owner,Personal use,Black,"$16,823"
...,...,...,...,...,...,...,...,...,...
6598,2018,GMC,Sierra 1500,"32,048",No accidents,1 Owner,Personal use,White,"$40,386"
6599,2019,Dodge,Grand Caravan,"70,527",No accidents,1 Owner,Personal use,Silver,"$18,995"
6600,2004,Toyota,Camry Solara,"111,089",1 accident,3 Owners,Personal use,White,"$6,999"
6601,2014,Volkswagen,Passat,"98,583",No accidents,1 Owner,Personal use,Gray,"$9,998"
6602,2020,Toyota,Camry,"39,059",No accidents,1 Owner,Personal use,Black,"$23,981"

In [165]:

#df.to_csv('car_before_clean.csv')

In [154]:
#df2=pd.read_csv("car_before_clean.csv")